// <auto-generated />
using System;
using EnableFront.Builder.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnableFront.Builder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824223202_AddImageUrlToSeries")]
    partial class AddImageUrlToSeries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnableFront.Builder.Domain.Entities.NormalizedAttendance", b =>
                {
                    b.Property<Guid>("AttendanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attended")
                        .HasColumnType("bit");

                    b.Property<decimal?>("DurationPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailDomain")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FirstJoinAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLeaveAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AttendanceId");

                    b.HasIndex("SessionId", "EmailDomain");

                    b.HasIndex("OwnerUserId", "SessionId", "Email")
                        .IsUnique();

                    b.ToTable("NormalizedAttendances");
                });

            modelBuilder.Entity("EnableFront.Builder.Domain.Entities.NormalizedRegistration", b =>
                {
                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailDomain")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RegistrationId");

                    b.HasIndex("SessionId", "EmailDomain");

                    b.HasIndex("OwnerUserId", "SessionId", "Email")
                        .IsUnique();

                    b.ToTable("NormalizedRegistrations");
                });

            modelBuilder.Entity("EnableFront.Builder.Domain.Entities.Series", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SeriesId");

                    b.HasIndex("OwnerUserId", "CreatedAt");

                    b.HasIndex("OwnerUserId", "Title")
                        .IsUnique();

                    b.ToTable("Series");
                });

            modelBuilder.Entity("EnableFront.Builder.Domain.Entities.SeriesMetrics", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalAttendees")
                        .HasColumnType("int");

                    b.Property<int>("TotalRegistrations")
                        .HasColumnType("int");

                    b.Property<int>("UniqueAccountsInfluenced")
                        .HasColumnType("int");

                    b.Property<int>("UniqueRegistrantAccountDomains")
                        .HasColumnType("int");

                    b.Property<string>("WarmAccounts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeriesId");

                    b.ToTable("SeriesMetrics");
                });

            modelBuilder.Entity("EnableFront.Builder.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionId");

                    b.HasIndex("SeriesId", "StartsAt");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("EnableFront.Builder.Domain.Entities.SessionMetrics", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalAttendees")
                        .HasColumnType("int");

                    b.Property<int>("TotalRegistrations")
                        .HasColumnType("int");

                    b.Property<int>("UniqueAttendeeAccountDomains")
                        .HasColumnType("int");

                    b.Property<int>("UniqueRegistrantAccountDomains")
                        .HasColumnType("int");

                    b.Property<string>("WarmAccountsTriggered")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionId");

                    b.ToTable("SessionMetrics");
                });

            modelBuilder.Entity("EnableFront.Builder.Domain.Entities.NormalizedAttendance", b =>
                {
                    b.HasOne("EnableFront.Builder.Domain.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnableFront.Builder.Domain.Entities.NormalizedRegistration", b =>
                {
                    b.HasOne("EnableFront.Builder.Domain.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnableFront.Builder.Domain.Entities.SeriesMetrics", b =>
                {
                    b.HasOne("EnableFront.Builder.Domain.Entities.Series", null)
                        .WithOne()
                        .HasForeignKey("EnableFront.Builder.Domain.Entities.SeriesMetrics", "SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnableFront.Builder.Domain.Entities.Session", b =>
                {
                    b.HasOne("EnableFront.Builder.Domain.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnableFront.Builder.Domain.Entities.SessionMetrics", b =>
                {
                    b.HasOne("EnableFront.Builder.Domain.Entities.Session", null)
                        .WithOne()
                        .HasForeignKey("EnableFront.Builder.Domain.Entities.SessionMetrics", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
